### ISSUE TITLE
Roadkill

### ISSUE THREAD

**Issue by jus61** [Defent/DMS_Exile#11]
Please disable Roadkill

**Comment by eraser1** [comment]
Please clarify what you mean :)

**Comment by jus61** [comment]
the player shout not be able to overdrive the Ki (AI)

**Comment by eraser1** [comment]
Give the AI rocket launchers :)

I will also be adding support for static AI soon...

**Comment by jus61** [comment]
Have we already

**Comment by eraser1** [comment]
I will be working on this feature soon. However, keep in mind, this feature will not be compatible with DMS_ai_offload_to_client

**Comment by jus61** [comment]
Thx
