### ISSUE TITLE
kicked for Script Restriction #39??

### ISSUE THREAD

**Issue by jus61** [Defent/DMS_Exile#12]
in to the Line 41 (script.txt)

!=“e \“lastGestFreezeT\”;\n\nif (_VBtemp + 25 < time) then\n{\n\nif (isPlayer _this) then {}\nelse\n{\nif (random 10 < 6) then\n{\n\nif”

**Comment by eraser1** [comment]
If you add that to the end, and use RCON to "reload scripts" or restart the server, that should prevent those kicks.
