### ISSUE TITLE
PBO

### ISSUE THREAD

**Issue by Vaporiz3** [Defent/DMS_Exile#17]
hi guys im following the instructions in the pbo but i cant seem to see it working in game i have put the pbo in my exileserver addons folder and im unsure as to why there is an X for the x\addons\blahhh if there are no other folders before the dir if there all contained in the pbo? can you please give me a few steps to get this working as i cant get it working. im on linux debian 8

**Comment by Defent** [comment]
x is there for the arma engine to verify and check the location of the scripts, this is defiend in the pboprefix files. It can also be changed to q but I generally use x. One of the reasons as to why it does not work is because Linux only supports lower case. I'm pretty sure that the directories and folder lines have some upper case letters in them. You'll have to change this yourself if you want it to work on linux.

**Comment by Vaporiz3** [comment]
I got it to initilize last night however it did not seem to load in game like no missions started etc any other pointers i can play with as to why this does not work dude?

**Comment by Defent** [comment]
Change upper case to lower case.

**Comment by Vaporiz3** [comment]
17:39:26 "DMS :: Initializing Mission Variables"
17:39:26 "ExileServer - Main thread started"
17:39:26 "Voodoo/BIS_fnc_log: [postInit] DMS_fnc_DMS_postInit (30.0064 ms)"
17:39:26 "DMS :: Initializing FSM mission script"
17:42:40 Vaporiz3 uses modified data file

**Comment by eraser1** [comment]
Did you change all the file names/paths to lowercase?

**Comment by Vaporiz3** [comment]
just going through it now just wondering how about this one does it need to be lowercase aswell dude? DMS_HC_Object = objNull;

**Comment by eraser1** [comment]
I'm pretty sure you can leave variables lowercase. It's only the file and folder names, as well as the names in the config.

**Comment by Vaporiz3** [comment]
hmm ok thanks
ill update shortly

**Comment by Vaporiz3** [comment]
ill try and update in a moment

**Comment by Vaporiz3** [comment]
8:23:09 "Voodoo/BIS_fnc_log: [postInit] ExileServer_fnc_postInit (73963 ms)"
18:23:09 "DMS :: Initializing FSM mission script"
18:23:09 "ExileServer - Main thread started"
18:23:10 Inventory item with given name: [Rangefinder] not found
18:24:27 "ExileServer - GetObjectContainerCargo - []"

is what i get... all files and folders are lowercase

heres my config.cpp

class CfgPatches
{
    class A3_dms
    {
        units[] = {};
        weapons[] = {};
        a3_dms_version = 3.0;
        requiredversion = 1.36;
        requiredaddons[] = {"e@exileserverile_client","e@exileserverile_server_config"};
    };
};
class CfgFunctions
{
    class dms
    {
        class main
        {
            file = "\@exileserver\addons\dms";
            class dms_preinit
            {
                preInit = 1;
            };
            class dms_postinit
            {
                postInit = 1;
            };
        };
        class compiles
        {
            file = "\@exileserver\addons\dms\scripts";
            class addmissiontomonitor           {};
            class ailocalitymanager             {};
            class broadcastmissionstatus        {};
            class cleanup                       {};
            class cleanupmanager                {};
            class createmarker                  {};
            class fillcrate                     {};
            class findsafepos                   {};
            class findsuppressor                {};
            class isplayernearby                {};
            class isnearwater                   {};
            class missionsmonitor               {};
            class missionsuccessstate           {};
            class onkilled                      {};
            class removemarkers                 {};
            class selectmagazine                {};
            class selectmission                 {};
            class setailocality                 {};
            class setgroupbehavior              {};
            class spawnaigroup                  {};
            class spawnaisoldier                {};
            class spawncrate                    {};
            class spawnnonpersistentvehicle     {};
            class targetskilled                 {};
        };
    };
};

my preinit

/*
    DMS Pre-init
    Written by eraser1 (trainwreckdayz.com)
*/

/\* Future stuff
DMS_SpawnStatic         = compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\scripts\spawnstatic.sqf";
DMS_HeliPara            = compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\scripts\helipara.sqf";
DMS_HeliPatrol          = compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\scripts\helipatrol.sqf";
DMS_VehPatrol           = compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\scripts\vehpatrol.sqf";
DMS_VehMonitor          = compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\scripts\vehmonitor.sqf";
*/

DMS_HC_Object = objNull;

//Load config
call compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\config.sqf";

my post init

/*
    Launches mission functions
    Made for Defent for Defents Mission System
    And for Numenadayz.com
    Written by eraser1
*/

RESISTANCE setFriend[WEST,0];
WEST setFriend[RESISTANCE,0];
RESISTANCE setFriend[EAST,0];
EAST setFriend[RESISTANCE,0];
EAST setFriend[WEST,0];
WEST setFriend[EAST,0];

if(DMS_StaticMission) then
{
    call compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\static\static_init.sqf";//<---- TODO
};

if (DMS_DynamicMission) then
{
    call compileFinal preprocessFileLineNumbers "\@exileserver\addons\dms\missions\mission_init.sqf";
    execFSM "\@exileserver\addons\dms\fsm\missions.fsm";
};

**Comment by eraser1** [comment]
Set DMS_DEBUG to true in config :)

**Comment by Vaporiz3** [comment]
Data file too short '/home/steam/arma3/@exileserver\addons\a3_dms.pbo'. Expected 154027 B, got 142352 B

got that now

**Comment by Vaporiz3** [comment]
and these before i restarted... 18:23:09   Error Undefined variable in expression: exileserverislocked
18:23:09 File exile_server\code\ExileServer_system_rcon_event_ready.sqf, line 10
18:23:09 "Voodoo/BIS_fnc_log: [postInit] ExileServer_fnc_postInit (73963 ms)"
18:23:09 "DMS :: Initializing FSM mission script"
18:23:09 "ExileServer - Main thread started"
18:23:10 Inventory item with given name: [Rangefinder] not found
18:24:27 "ExileServer - GetObjectContainerCargo - []"
18:26:16 "ExileServer - GetObjectContainerCargo - []"
18:28:20 Client: Remote object 3:0 not found
18:28:35 "ExileServer - GetObjectContainerCargo - []"
18:32:09 Warning Message: Script x\addons\DMS\missions\donthasslethehoff.sqf not found
18:47:09 Warning Message: Script x\addons\DMS\missions\mercenaries.sqf not found
^C18:52:24 Deinitialized shape [Class: "Underwear_F"; Shape: "a3\characters_f\common\basicbody.p3d";]

**Comment by eraser1** [comment]
Change "DMS" to "dms" in fn_selectMission.sqf

**Comment by Vaporiz3** [comment]
20:46:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"


keeps asking this... does this mean i have to go through each file and change from upper to lower case?

**Comment by Vaporiz3** [comment]
20:47:19 Warning Message: Script x\addons\dms\missions\beertransport.sqf not found

**Comment by Vaporiz3** [comment]
20:46:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:46:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:47:04 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:47:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SelectMission"
20:47:19 "dms_DEBUG SelectMission :: Spawning mission: beertransport | dms_BMissionDelay set to 53.9754"
20:47:19 Warning Message: Script x\addons\dms\missions\beertransport.sqf not found
20:47:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:47:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:47:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:48:04 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:48:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SelectMission"
20:48:19 "dms_DEBUG SelectMission :: Spawning mission: cardealer | dms_BMissionDelay set to 44.1902"
20:48:19 Warning Message: Script x\addons\dms\missions\cardealer.sqf not found
20:48:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:48:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:48:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:49:04 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:49:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SelectMission"
20:49:19 "dms_DEBUG SelectMission :: Spawning mission: humanitarian | dms_BMissionDelay set to 30.6695"
20:49:19 Warning Message: Script x\addons\dms\missions\humanitarian.sqf not found
20:49:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:49:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:49:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:50:04 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:50:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SelectMission"
20:50:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:50:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor

20:49:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:49:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:49:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:50:04 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:50:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SelectMission"
20:50:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:50:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:50:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:51:04 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:51:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_CleanUpManager"
20:51:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SelectMission"
20:51:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:51:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SetAILocality"
20:51:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:51:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:52:04 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:52:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_SelectMission"
20:52:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:52:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:52:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"

Do i need to change upper case to lowercase? for all classes throughout the whole mod?

**Comment by Vaporiz3** [comment]
20:48:19 Warning Message: Script x\addons\dms\missions\cardealer.sqf not found
20:48:19 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:48:34 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"
20:48:49 "DMS_DEBUG FSM CHECK :: calling DMS_fnc_MissionsMonitor"

**Comment by Vaporiz3** [comment]
Do i need to change upper case to lowercase? for all classes throughout the whole mod?

**Comment by eraser1** [comment]
Linux doesn't support uppercase file paths, that's the only thing you should have needed to change.

Can you unpack the PBO that you're packing and ensure that your PBO tool is using the prefix?

**Comment by Vaporiz3** [comment]
i changed the prefix to erm \@exileserver\addons\dms

**Comment by Vaporiz3** [comment]
When i use \x\ i get the file cant be found and it doesnt initialize

**Comment by Vaporiz3** [comment]
Ok right, ive gone back to the start, ive changed the uppercase to lower case also with the classes in the conf file.

I have also changed each folder and file in the pbo to lower case to match.

I get this error when trying to start.

21:24:06 PhysX3 SDK Init started ...
21:24:06 PhysX3 SDK Init ended.
21:24:07 Warning Message: Script x\addons\dms\fn_dms_preinit.sqf not found
21:24:07 Warning Message: Script x\addons\dms\fn_dms_postinit.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_addmissiontomonitor.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_ailocalitymanager.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_broadcastmissionstatus.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_cleanup.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_cleanupmanager.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_createmarker.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_fillcrate.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_findsafepos.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_findsuppressor.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_isplayernearby.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_isnearwater.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_missionsmonitor.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_missionsuccessstate.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_onkilled.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_removemarkers.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_selectmagazine.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_selectmission.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_setailocality.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_setgroupbehavior.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_spawnaigroup.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_spawnaisoldier.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_spawncrate.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_spawnnonpersistentvehicle.sqf not found
21:24:07 Warning Message: Script x\addons\dms\scripts\fn_targetskilled.sqf not found

where do i go from here...

**Comment by Vaporiz3** [comment]
I also dont understand why there is a prefix of \x\blah\blahh\DMS should i make this lower case and is the prefix used to sort of make the script more streamlined as such?

I understand why i have to make files and folders upper and lower case which i have done aswell as edited the dirs to files from uppercase to lower case in the classes in the conf file.

**Comment by Vaporiz3** [comment]
http://www92.zippyshare.com/v/cG28m01j/file.html

any chance you could look at that pbo for me... just to see whats going on please?

**Comment by eraser1** [comment]
Just make the prefix lowercase... don't change any of the actual letters in them.

I looked at your PBO. It appears the prefix is not being applied. What PBO tool are you using?

**Comment by Vaporiz3** [comment]
PBO manager

**Comment by Vaporiz3** [comment]
Just to clarify, do you want me to leave the X the same through the whole prefix and postprefix stuff aswell as the other files and just change the names of all files and folders to lowercase?

**Comment by eraser1** [comment]
Yes... the only changes you should be making are in the config.sqf, or changing stuff to lower case.
