### ISSUE TITLE
Map Markers and Mission Names

### ISSUE THREAD

**Issue by CEN-ATD** [Defent/DMS_Exile#18]
Would like to see the map markers not be 100% centered on where the mission is, and same with the black dot and mission name.

Give it a radius of 300-500m where the mission is WITHIN the marker, but not centered on it so players don't know exactly where it is each time.

**Comment by eraser1** [comment]
Good idea!

I'll make random marker positioning a config value, as well as add an ability to "force" random positioning of the marker by the mission. This will enable future "treasure hunt" missions without AI :)

**Comment by eraser1** [comment]
Implemented :)
