### ISSUE TITLE
Using the release system

### ISSUE THREAD

**Issue by KawaiiPotato** [Defent/DMS_Exile#19]
https://github.com/blog/1547-release-your-software

I shouldn't have to explain the feature but using releases mean that it is clear to users where to get the versions and what is "safe" to put on their servers.

**Comment by eraser1** [comment]
Thanks for the tip!

I tend to use branches when testing stuff, so everything on the main branch should be relatively "safe" to put into the server.

I will look into "Releases" for putting out changelogs though :)

**Comment by KawaiiPotato** [comment]
This is the best way to contact you, http://puu.sh/k5a1n/c7bda3ed58.png
I scrubbed the stockphoto thing.
