### ISSUE TITLE
AI don't attack vehicles

### ISSUE THREAD

**Issue by Onefox** [Defent/DMS_Exile#22]
I would be cool if the AI will wreck your wheels, i only saw them shooting on a helicopter, but not on a strider, players just run all the AI over and get the boxes.

**Comment by eraser1** [comment]
That's an issue with how ArmA handles AI unfortunately... it was actually just "patched" in 1.50. I am working on a few things to discourage that though; I have already added an option to reduce poptabs/respect when you run an AI over ;)

**Comment by Onefox** [comment]
What do you mean with "patched" they fucked it up with 1.50?

**Comment by eraser1** [comment]
Pretty much :p

**Comment by Onefox** [comment]
so lets cross fingers that it will get better again :D another option would be to spawn mines around the mission.. so you cant drive in there.

**Comment by eraser1** [comment]
That's at the top of my to-do list atm ;)

**Comment by Onefox** [comment]
cool, let me know if i could help.
