### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jus61** [Defent/DMS_Exile#3]
"DMS_SpawnAIGroup :: Spawned 6 AI at [9888.95,7407.17,0]."
 2:18:38 Error in expression <FromQueue = true;
}
else 
{
_newOwner = owner _player;
if (typeName _entity == ">
 2:18:38   Error position: <owner _player;
if (typeName _entity == ">
 2:18:38   Error owner: Type Group, expected Object
 2:18:38 File exile_server\code\ExileServer_system_swapOwnershipQueue_thread_dispatchQueue.sqf, line 23

**Comment by eraser1** [comment]
I never got around to testing client offload of AI. Thanks for the report, looking into it now :)

**Comment by eraser1** [comment]
We had the arguments on backwards LOL. Should be fixed now :P
