### ISSUE TITLE
DMS not loading

### ISSUE THREAD

**Issue by Onefox** [Defent/DMS_Exile#31]
I get the following things in the log, 
19:27:54 "@ExileServer/BIS_fnc_log: [preInit] DMS_fnc_DMS_preInit (0 ms)"
19:27:59 "@ExileServer/BIS_fnc_log: [postInit] DMS_fnc_DMS_postInit (0 ms)"

And DMS is not loading correctly, i can't really explain why this is happening i tried many different options.

Here is the full log: http://pastebin.com/6xe44UrY

**Comment by eraser1** [comment]
Can you unpack the PBO and ensure that the correct prefix was applied?

Unpacking should produce a file structure similar to the one in github: "\x\addons\dms"

**Comment by Onefox** [comment]
Mmh i found the reason, but i cant explain it to me... If i take the pbo from here without touching it its working.
if i just unpack it with PBO Manager 1.4 Beta (I use that tool for ever edit) and pack it again i get the 0 ms in the log and it doesn't work.

But why? I use the Manager for everything... 

Okey i guess its a bug for the PBO Manager.....
When i unpack it the $PBOPREFIX$ file is missing, than when i repack it its not working.
When i unpack it and add the $PBOPREFIX$ again and than repack it its workering :+1: 

Since the other pbo are not depended on the $PBOPREFIX$ file its working for all of them..

**Comment by eraser1** [comment]
PBO Prefixes are weird :P
