### ISSUE TITLE
Error Undefined variable in expression: dms_randombanditmissionsonstart

### ISSUE THREAD

**Issue by koriaba** [Defent/DMS_Exile#46]
Hi. is such a record

22:25:02 "DMS_SpawnAIGroup_MultiPos :: Spawned 31 AI using positions parameter: [[8435.86,25050.7,0],[8424.41,25054.5,0],[8473.88,25057.6,0],[8467.45,25054.6,0],[8480.42,25081.6,0],[8490.28,25075.3,0],[8549.45,25043.7,0],[8450.97,25177,0],[8440.4,25184.4,0],[8400.37,25149.9,0.753296],[8479.99,25185.3,0],[8484.67,25182.5,0],[8488.71,25179.6,0],[8493.91,25162.5,0],[8543.77,25149.9,0],[8551.9,25119.1,0],[8514.54,25097.9,0],[8483.86,25110.1,0],[8435.38,25116.4,0],[8447.62,25104.2,0],[8438.01,25135.3,0],[8436.95,25170.6,0],[8442.45,25198.6,0],[8449.65,25207.8,0],[8381.02,25109.4,0],[8379.57,25116.6,0],[8415.75,25011.5,0],[8490.89,25135.1,0],[8512.8,25124.9,0],[8518.46,25095.5,0],[8519.71,25092.4,0],[8533.05,25098.9,0],[8463.94,25163.6,0],[8476.27,25123.1,4.00956],[8476.27,25123.1,4.00956],[8476.27,25123.1,4.00956]]."
22:25:03 "ExileServer - Job with handle 10007 added."
22:25:04 "ExileServer - Job with handle 10008 added."
22:25:04 "DMS_DEBUG :: DMS post-init complete. productVersion: ["Arma 3","Arma3",162,137494,"Stable",true,"Windows"] | infiSTAR version: not installed |::|::| (DMS_Version: "September 5, 2016" | time: 196.014 | diag_tickTime: 272.367 | 18.9573 FPS)"
22:25:04 Error in expression <stance = _temp;
};

for "_i" from 1 to DMS_RandomBanditMissionsOnStart do
{
[se>
22:25:04   Error position: <DMS_RandomBanditMissionsOnStart do
{
[se>
22:25:04   Error Undefined variable in expression: dms_randombanditmissionsonstart
22:25:04 File x\addons\dms\fn_DMS_postInit.sqf, line 252
22:25:04 "@ExileServer/BIS_fnc_log: [postInit] DMS_fnc_DMS_postInit (30010 ms)"

**Comment by eraser1** [comment]
You did not update your config. Please read [the changelog](https://github.com/Defent/DMS_Exile/wiki/Changelog) for [new config values](https://github.com/Defent/DMS_Exile/wiki/Changelog#july-26-2016-930-pm-cst-america) when updating DMS.

**Comment by koriaba** [comment]
Yes, I confess, too lazy to re-adjust. I took the configuration from the previous version.
