### ISSUE TITLE
DMS No Door open

### ISSUE THREAD

**Issue by HellBz** [Defent/DMS_Exile#51]
Now DMS spawned Buildings/Objects Doors cannot be opend.

is this a BUG ??

**Comment by ravmustang** [comment]
New arma 3 system called dynamic simulation. 

Objects need to have enableDynamicSimulation true set.
But also in order for that to work, exile needs to turn on the triggering system to the players. 
Look for Cloud and Torndeco work on extdb3, which includes all fixes

**Comment by HellBz** [comment]
No this fix not all All Doors can be opend, but not the doors spawned by DMS Script-...

**Comment by ravmustang** [comment]
For example
fn_ImportFromM3E.sqf
Line 57 or so. 
_obj enableSimulationGlobal false;
Needs to become 
_obj enableDynamicSimulation true;
For all buildings with doors. 

But these changes also rely on your exile server being compatible with dynamic simulation as well

**Comment by Monkeynutz2010** [comment]
I changed all enableSimulationGlobal instances in the DMS code to enableDynamicSimulation, i am running it as a test tonight. will get back with results on how server performance is changed.

**Comment by ravmustang** [comment]
Check merge #53 for these changes to DMS ;)

**Comment by eraser1** [comment]
Should be fixed
