### ISSUE TITLE
_weaponAttachments optic dont spawn

### ISSUE THREAD

**Issue by syn7ax** [Defent/DMS_Exile#56]
clean exile-server installation.
only dms. 

optics dont spawn
"optic spawn chance 100"

**Comment by 1datatec** [comment]
In fn_SpawnAISoldier.sqf file have to remove the whole USE_EXTRA_CHECKING block

**Comment by eraser1** [comment]
You don't have to remove anything @dimashinb , just comment out [this line](https://github.com/Defent/DMS_Exile/blob/master/%40ExileServer/addons/a3_dms/scripts/fn_SpawnAISoldier.sqf#L35)

**Comment by 1datatec** [comment]
I think i tried it, but it didnt work for me back then.

**Comment by eraser1** [comment]
It should, unless BIS fucked up preprocessor directives along with config info.

**Comment by syn7ax** [comment]
it worked! just comment out [this line](https://github.com/Defent/DMS_Exile/blob/master/%40ExileServer/addons/a3_dms/scripts/fn_SpawnAISoldier.sqf#L35)!

@eraser1 "#define USE_EXTRA_CHECKING 1" to "#define USE_EXTRA_CHECKING 0" wont work?

**Comment by eraser1** [comment]
@syn7ax No, because the script (preprocessor) only checks if the identifier is defined, it doesn't check the value.

**Comment by eraser1** [comment]
Fixed a while ago, will look into fixing the feature later (maybe)
