### ISSUE TITLE
DMS - "Mission Cleanup settings"

### ISSUE THREAD

**Issue by AKATONYEXILE** [Defent/DMS_Exile#58]
/*Mission Cleanup settings*/
	DMS_CompletedMissionCleanup			= true;					// Cleanup mission-spawned buildings and AI bodies after some time
	DMS_CompletedMissionCleanupTime		= 300;					// Minimum time until mission-spawned buildings and AI are cleaned up
	DMS_CleanUp_PlayerNearLimit			= 50;					// Cleanup of an object is aborted if a player is this many meters close to the object
	DMS_AIVehCleanUpTime				= 300;					// Time until a destroyed AI vehicle is cleaned up.
	/*Mission Cleanup settings*/

My settings and the problem, after the mission has been marked as complete the AI-Corpses, Vehicles dont cleanup and just stay there. How to solve this?

**Comment by eraser1** [comment]
All of those should be handled by Exile cleanup.
