### ISSUE TITLE
AI gear drop chance

### ISSUE THREAD

**Issue by UnPure** [Defent/DMS_Exile#6]
Hey there.

Would it be possible to add a config option to remove the gear from dead AI's with a percentage?
So like 20% of the bots will drop the weapons when they die, all others are without a weapon?

Sorry for my bad english, i hope its not to hard to understand.

**Comment by Defent** [comment]
Yes, if you check this code: https://github.com/Defent/DMS_Exile/blob/master/%40ExileServer/addons/a3_dms/scripts/OnKilled.sqf#L54

and the function: DMS_remove_roadkill_chance then you should be able to fix that.

**Comment by eraser1** [comment]
Implemented with https://github.com/Defent/DMS_Exile/commit/9af7f3f0ea51d82ec56d540380f8c7f7267b0264
