### ISSUE TITLE
Non-opening door

### ISSUE THREAD

**Issue by AntoineAngel** [Defent/DMS_Exile#63]
Hello, how can we open the doors of missions? Because some NPC enters the buildings but impossible to complete the mission without an admin is there.

**Comment by eraser1** [comment]
A door on a building will be unopenable (or unclosable) if simulation on the building is disabled.

Make sure when you import an object (building) with doors that simulation is set to be enabled on them.

**Comment by AntoineAngel** [comment]
How can I activate simulation on buildings?

**Comment by eraser1** [comment]
If you're using objects exported by M3E 3DEN, then the "simulation" flag is controlled by `((_x select 3) select 0)`, where `_x` is the subarray containing information for a specific object.

**Comment by eraser1** [comment]
Adding an additional option for the older M3 Editor to control simulation.

It will default to disabled simulation.
