### ISSUE TITLE
Godmode for ai while frozen

### ISSUE THREAD

**Issue by Xairooo** [Defent/DMS_Exile#69]
hey,

i tried to give the ai godmode when frozne with:
"_x allowdamage false;"  in fn_FreezeManager.sqf and fn_FreezeToggle.sqf.

but i didnt work. the ai was still getting damage.
what do i need to add to get it working?

**Comment by eraser1** [comment]
You would have to ensure the AI is local, and handle locality transfers.

That's the most obvious culprit that comes to mind anyways.
