### ISSUE TITLE
Map Marker for static missions not showing up

### ISSUE THREAD

**Issue by ehylla93** [Defent/DMS_Exile#73]
The problem stated in the topic occurs sometimes. AI will spawn, but the map marker is not showing.

**Comment by BadYpsilon** [comment]
Does the problem always occur on the same mission or on different missions?

**Comment by ehylla93** [comment]
Nope, different missions on all my three servers. But only on static missions.

**Comment by DEH4NK** [comment]
Are there any errors in the RPT file? Show one of my static missions here.

**Comment by ehylla93** [comment]
Sadly there are no errors related to that problem.

There were some errors relatee to other missions, I fixed them but sadly the problem still occurs.

**Comment by Monkeynutz2010** [comment]
This is not an issue with DMS but an issue with the mission itself. Check it for errors.

**Comment by WyBrator** [comment]
Hello there I seem to be getting this Error with Static missions.

14:32:45 "DMS ERROR :: Calling DMS_fnc_ImportFromM3E_Static with invalid file/filepath: georgetown_buildings | _export: <null>"
14:32:45 Error in expression < file/filepath: %1 | _export: %2",_file,_export];
[]
};

private _objs = _export>
14:32:45   Error position: <_export];
[]
};

private _objs = _export>
14:32:45   Error Undefined variable in expression: _export
14:32:45 File x\addons\dms\scripts\fn_ImportFromM3E_Static.sqf..., line 42
14:32:45 Attempt to override final function - dms_staticmission_georgetown

**Comment by KASASBAHIA** [comment]
alguém tem essa missão DMS com premiação em poptabs e com um BOX que possa ser transportado?
