### ISSUE TITLE
Mission locations

### ISSUE THREAD

**Issue by EWSG2020** [Defent/DMS_Exile#74]
Hi,

I can't figure out why all missions are always on the west side of the (Tanoa) map... Has this issue been noted before??

I'd like to have them spread out over the entire map but currenty almost all missions spawn on the SW and NW island. I am wondering if this configurable or do I need to use the fixed positions to do this??

I enclosed 3 screenshots with mission locations after restarting the server. I also enclosed the config and tanoa_config in docx format.

The config also seems to ignore line 141: "DMS_MissionNearBlacklist = 2500;".

![image](https://user-images.githubusercontent.com/76768291/103336483-9a49f080-4a78-11eb-8dd6-805a48e43894.png)

![image](https://user-images.githubusercontent.com/76768291/103336869-c9149680-4a79-11eb-8b86-bfbcd5249da1.png)

![image](https://user-images.githubusercontent.com/76768291/103337761-9d46e000-4a7c-11eb-81f5-369a0fae0cb5.png)

[config.docx](https://github.com/Defent/DMS_Exile/files/5753397/config.docx)

[tanoa_config.docx](https://github.com/Defent/DMS_Exile/files/5753398/tanoa_config.docx)

**Comment by eraser1** [comment]
Those locations are the most likely to fit the requirements of "openness" after performing random searches.

The "mission near" requirement is also relaxed after sufficient failed searches.

I recommend using fixed locations, and simply generate enough fixed locations such that it seems random.
