### ISSUE TITLE
Someone has stolen your work and is using it in violation of your licensing as a DayZ commercial mod.

### ISSUE THREAD

**Issue by lordkabal26** [Defent/DMS_Exile#75]
https://steamcommunity.com/sharedfiles/filedetails/?id=2518296950

"To learn more about this mod, or how to obtain a license to use this mod, please visit our Discord! We are happy to answer any questions or offer help. (Discord Server Invite Code : 8kEGHqtpK7)."

**Comment by eraser1** [comment]
The author claims to be "inspired" by this work, which may be the case as far as I know.

Regardless, the mod is for a different game as far as I'm concerned, and I'm sure the effort required to convert it was substantial.

While I would appreciate if derivative works were open sources, I no longer have the time to enforce those wishes.
