### ISSUE TITLE
Error in report with Static missions

### ISSUE THREAD

**Issue by MrVibesRSA** [Defent/DMS_Exile#76]
14:32:45 "DMS ERROR :: Calling DMS_fnc_ImportFromM3E_Static with invalid file/filepath: georgetown_buildings | _export: <null>"
14:32:45 Error in expression < file/filepath: %1 | _export: %2",_file,_export];
[]
};

private _objs = _export>
14:32:45   Error position: <_export];
[]
};

private _objs = _export>
14:32:45   Error Undefined variable in expression: _export
14:32:45 File x\addons\dms\scripts\fn_ImportFromM3E_Static.sqf..., line 42
14:32:45 Attempt to override final function - dms_staticmission_georgetown

**Comment by eraser1** [comment]
You provided a path called "georgetown_buildings", but there is no "georgetown_buildings.sqf" file in the static missions folder to define the objects to spawn.

I recommend visiting the Exilemod discord and asking for help in the appropriate channel.
