### ISSUE TITLE
Question: Function decleration

### ISSUE THREAD

**Issue by Windmolders** [Defent/DMS_Exile#9]
Is it no better to declare the function in the config.cpp/bin ( as considered best way to declare them according to some a3 experts)?

**Comment by Defent** [comment]
That does sound like a nice idea, but what is the benefits from it?

**Comment by Windmolders** [comment]
It's the same as your pre_init file. It's declared in your config. It looks way cleaner. And as far as i heard it's the best way to do it. I don't have really good arguments myself haha :palm_tree:

**Comment by eraser1** [comment]
Can you provide an example as to how it would be called/defined? :)

**Comment by Windmolders** [comment]
Sure,

https://github.com/DevZupa/ZCP-A3/blob/master/a3_epoch_server_zcp/config.cpp

**Comment by eraser1** [comment]
Looks good... except I will have to rename everything T_T. Unless there is a way to not have it be automatically prefixed with "fn_"

**Comment by ghost** [comment]
Just use notepad++ and do it with a macro. That's how i did my 44 jobs on my scheduler.

**Comment by eraser1** [comment]
Yeah, I can do it. I'm just lazy :P

This will probably be one of the first things I do after I'm done with HC testing.

**Comment by eraser1** [comment]
Working on this now... thanks for the tip Zupa. Will add you to the readme :)
